# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 638)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.F5simulator = QtWidgets.QPushButton(parent=self.centralwidget)
        self.F5simulator.setGeometry(QtCore.QRect(380, 440, 91, 61))
        self.F5simulator.setStyleSheet("background-color: rgb(186, 186, 186);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.F5simulator.setObjectName("F5simulator")
        self.The_Code = QtWidgets.QLabel(parent=self.centralwidget)
        self.The_Code.setGeometry(QtCore.QRect(40, 30, 361, 361))
        self.The_Code.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.The_Code.setObjectName("The_Code")
        self.Result = QtWidgets.QLabel(parent=self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(450, 30, 361, 361))
        self.Result.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Result.setObjectName("Result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.action.triggered.connect(lambda: self.clicked("g"))



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.F5simulator.setText(_translate("MainWindow", "F5"))
        self.The_Code.setText(_translate("MainWindow", "write the code"))
        self.Result.setText(_translate("MainWindow", "the code is false"))
    
    def clicked(self, text):
        self.The_Code.setText(text)
        self.The_Code.adjustSize()
    
    def clicked(self, text):
        self.Result.setText(text)
        self.Result.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
